package it.water.connectors.kafka.service.rest;

import it.water.connectors.kafka.api.KafkaConnectorApi;
import it.water.connectors.kafka.api.rest.KafkaConnectorRestApi;
import it.water.connectors.kafka.model.ACLConfig;
import it.water.connectors.kafka.model.ConnectorConfig;
import it.water.connectors.kafka.model.KafkaConnector;
import it.water.connectors.kafka.model.TopicConfig;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import lombok.Setter;
import org.apache.kafka.clients.admin.CreateAclsResult;
import org.apache.kafka.clients.admin.CreateTopicsResult;
import org.apache.kafka.clients.admin.DeleteAclsResult;
import org.apache.kafka.clients.admin.DeleteTopicsResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.core.Response;
import java.util.Arrays;


/**
 * @Generated by Water Generator
 * Rest API class for Kafka integration operations.
 *
 */
@FrameworkRestController(referredRestApi = KafkaConnectorRestApi.class)
public class KafkaConnectorRestControllerImpl implements KafkaConnectorRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(KafkaConnectorRestControllerImpl.class.getName());

    @Inject
    @Setter
    private KafkaConnectorApi kafkaConnectorApi;

    @Override
    public Response checkModuleWorking() {
        log.debug("In Rest Service GET /kafka/module/status");
        return Response.ok("Water Kafka Connector Module works!").build();
    }

    @Override
    public Response addConnector(ConnectorConfig connectorConfig) {
        log.debug("In REST Service POST /kafka/connectors");
        try {
            KafkaConnector connector = kafkaConnectorApi.addNewConnector(connectorConfig.getName(), connectorConfig);
            return Response.ok().entity(connector).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response updateConnector(String instanceName, ConnectorConfig connectorConfig) {
        log.debug("In REST Service PUT /kafka/connectors/{}", instanceName);
        try {
            KafkaConnector connector = kafkaConnectorApi.updateConnector(instanceName, connectorConfig);
            return Response.ok().entity(connector).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response deleteConnector(String instanceName) {
        log.debug("In REST Service DELETE /kafka/connectors/{}", instanceName);
        try {
            kafkaConnectorApi.deleteConnector(instanceName, true);
            return Response.ok().entity("Connector deleted.").build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response createTopic(TopicConfig topicConfig) {
        log.debug("In REST Service POST /kafka/topic: {}", topicConfig);
        try {
            CreateTopicsResult result = kafkaConnectorApi.adminCreateTopic(
                    topicConfig.getTopic(), topicConfig.getNumPartition(), topicConfig.getReplicationFactor());
            return Response.ok().entity(result).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response createMultipleTopics(TopicConfig[] topicsConfig) {
        if (log.isDebugEnabled()) {
            log.debug("In REST Service POST /kafka/topics: {}", Arrays.toString(topicsConfig));
        }
        try {
            String[] topics = new String[topicsConfig.length];
            int[] numPartitions = new int[topicsConfig.length];
            short[] numReplicas = new short[topicsConfig.length];
            for (int i = 0; i < topicsConfig.length; i++) {
                topics[i] = topicsConfig[i].getTopic();
                numReplicas[i] = topicsConfig[i].getReplicationFactor();
                numPartitions[i] = topicsConfig[i].getNumPartition();
            }
            CreateTopicsResult result = kafkaConnectorApi.adminCreateTopic(topics, numPartitions, numReplicas);
            return Response.ok().entity(result).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response dropTopics(String[] topics) {
        if (log.isDebugEnabled()) {
            log.debug("In REST Service DELETE /kafka/topics: {}", Arrays.toString(topics));
        }
        try {
            DeleteTopicsResult result = kafkaConnectorApi.adminDropTopic(Arrays.asList(topics));
            return Response.ok().entity(result).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response addACLs(ACLConfig aclConfig) {
        log.debug("In REST Service POST /kafka/acl: {}", aclConfig);
        try {
            CreateAclsResult result = kafkaConnectorApi.adminAddACLs(aclConfig.getUsername(), aclConfig.getPermissions());
            return Response.ok().entity(result).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

    @Override
    public Response deleteACLs(ACLConfig aclConfig) {
        log.debug("In REST Service DELETE /kafka/acl: {}", aclConfig);
        try {
            DeleteAclsResult result = kafkaConnectorApi.adminDeleteACLs(aclConfig.getUsername(), aclConfig.getPermissions());
            return Response.ok().entity(result).build();
        } catch (Throwable e) {
            return Response.serverError().entity(e.getMessage()).build();
        }
    }

}
