package it.water.connectors.kafka.api.rest;

import io.swagger.annotations.*;
import it.water.connectors.kafka.model.ACLConfig;
import it.water.connectors.kafka.model.ConnectorConfig;
import it.water.connectors.kafka.model.TopicConfig;
import it.water.core.api.service.rest.FrameworkRestApi;
import it.water.core.api.service.rest.RestApi;
import it.water.service.rest.api.security.LoggedIn;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

/**
 * @Generated by Water Generator
 * REST API for Kafka integration operations.
 */
@Path("/kafka")
@Api(produces = MediaType.APPLICATION_JSON, tags = "KafkaConnector API")
@FrameworkRestApi
public interface KafkaConnectorRestApi extends RestApi {
    @GET
    @Path("/module/status")
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "/kafka/module/status", notes = "Simple service for checking module status", httpMethod = "GET")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response checkModuleWorking();

    @POST
    @Path("/connectors")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/connectors", notes = "Add a new connector instance", httpMethod = "POST", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response addConnector(ConnectorConfig connectorConfig);

    @PUT
    @Path("/connectors/{instance_name}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/connectors/{instance_name}", notes = "Update connector configuration", httpMethod = "PUT", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response updateConnector(@PathParam("instance_name") String instanceName, ConnectorConfig connectorConfig);

    @DELETE
    @Path("/connectors/{instance_name}")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/connectors/{instance_name}", notes = "Delete connector", httpMethod = "DELETE", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response deleteConnector(@PathParam("instance_name") String instanceName);

    @POST
    @Path("/topic")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/topic", notes = "Creates a topic on Kafka", httpMethod = "POST", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response createTopic(TopicConfig topicConfig);

    @POST
    @Path("/topics")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/topics", notes = "Creates multiple topics on Kafka", httpMethod = "POST", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response createMultipleTopics(TopicConfig[] topicsConfig);

    @DELETE
    @Path("/topics")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/topics", notes = "Drops topics on Kafka", httpMethod = "DELETE", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response dropTopics(String[] topics);

    @POST
    @Path("/acl")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/acl", notes = "Creates Kafka ACLs", httpMethod = "POST", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response addACLs(ACLConfig aclConfig);

    @DELETE
    @Path("/acl")
    @Produces(MediaType.APPLICATION_JSON)
    @LoggedIn
    @ApiOperation(value = "/kafka/acl", notes = "Deletes Kafka ACLs", httpMethod = "DELETE", produces = "application/json", authorizations = @Authorization("jwt-auth"))
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful operation"),
            @ApiResponse(code = 403, message = "Not authorized"),
            @ApiResponse(code = 500, message = "Internal server error")
    })
    Response deleteACLs(ACLConfig aclConfig);
}
